name: Packaging ğŸ“¦

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      version_name:
        required: false
        type: string

jobs:
  package:
    name: Run production build ğŸ—ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          submodules: true

      - name: Setup node environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: npm
          check-latest: true

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Build native shell
        env:
          VERSION_NAME: ${{ inputs.version_name }}
        run: npm run build:nativeshell

      - name: Build web
        run: npm run build:web

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: package
          path: dist/package
